spring.application.name=salesapp
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@dbbooks_high?TNS_ADMIN=/app/wallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ADMIN}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:change-me}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.initialization-fail-timeout=-1

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${IDP_JWK_SET_URI:https://ghdevcompany.b2clogin.com/ghdevcompany.onmicrosoft.com/b2c_1_dn-gh/discovery/v2.0/keys}
salesapp.security.issuer=${IDP_ISSUER_URI:https://ghdevcompany.b2clogin.com/ac1dbc9b-27a4-4004-a719-42d96af26d37/v2.0/}

salesapp.api-manager.required=${SALESAPP_API_MANAGER_REQUIRED:false}
salesapp.api-manager.subscription-key=${SALESAPP_API_MANAGER_SUBSCRIPTION_KEY:dev-salesapp-key}
