INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Pan marraqueta', 'Panaderia', 1200, 50, 1);

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Leche entera 1L', 'Lacteos', 1190, 30, 1);

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Arroz grado 1 1kg', 'Despensa', 1490, 40, 1);

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Huevos docena', 'Frescos', 3290, 20, 1);

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Manzana roja 1kg', 'Frutas', 1890, 35, 1);

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA, PRECIO, STOCK, ACTIVO)
VALUES ('Aceite vegetal 900ml', 'Despensa', 2790, 25, 1);

COMMIT;
